config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'reports/show'
  get 'reports/new'
  get 'reports/create'
  get 'reports/edit'
  get 'reports/update'
  get 'reports/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :personas
  resources :opponents
  resources :reports

  root to: 'personas#new'
  get '/personas', to: 'personas#index', as: 'fighter'

  get '/you_attaque_cool', to: 'personas#you_attaque_cool', as: 'attaque_cool'
  get '/you_attaque_medium', to: 'personas#you_attaque_medium', as: 'attaque_medium'
  get '/you_attaque_hard', to: 'personas#you_attaque_hard', as: 'attaque_hard'
  get '/ia_attaque_cool', to: 'opponents#ia_attaque_cool', as: 'receive_cool'
  get '/ia_attaque_medium', to: 'opponents#ia_attaque_medium', as: 'receive_medium'
  get '/ia_attaque_hard', to: 'opponents#ia_attaque_hard', as: 'receive_hard'
  get '/choose_action', to: 'opponents#choose_action', as: 'choose_action'
  get '/win', to: 'personas#win', as: 'win'
  get '/loose', to: 'personas#loose', as: 'loose'
  get '/choix', to: 'personas#choix', as: 'choix'
  get '/choix1', to: 'personas#choix1', as: 'choix1'
  get '/choix2', to: 'personas#choix2', as: 'choix2'
  get '/choix3', to: 'personas#choix3', as: 'choix3'
  get '/choix4', to: 'personas#choix4', as: 'choix4'
  post '/name', to: 'personas#name', as: 'name'
end

app/models/persona.rb
# == Schema Information
#
# Table name: personas
#
#  id         :bigint           not null, primary key
#  avatarnum  :integer
#  name       :string
#  pa         :integer
#  pv         :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Persona < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :pv, presence: true
  validates :pa, presence: true
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  skip_before_action :verify_authenticity_token
  # GET method to get all products from database
  require 'faker'
  def index
    @personas = Persona.all
    render :loose if Persona.last.pv.zero?
    render :win if Opponent.last.pv.zero?
  end

  def index2
    @personas = Persona.all
    render :loose if Persona.last.pv.zero?
    render :win if Opponent.last.pv.zero?
  end

  # GET method to get a persona by id
  def show
    @persona = Persona.find(params[:id])
    render json: @persona
  end

  # GET method for the new persona form
  def new
    @persona = Persona.new
  end

  def choix; end

  def choix1
    @persona = Persona.new(name: Faker::JapaneseMedia::OnePiece.character, pv: 100, pa: 100, avatarnum: 1 )
    @persona.save
    if @persona.errors.empty?
      render :name
    else
      render :new
    end
  end

  def choix2
    @persona = Persona.new(name: Faker::JapaneseMedia::OnePiece.character, pv: 100, pa: 100, avatarnum: 2 )
    @persona.save
    if @persona.errors.empty?
      render :name
    else
      render :new
    end
  end

  def choix3
    @persona = Persona.new(name: Faker::JapaneseMedia::OnePiece.character, pv: 100, pa: 100, avatarnum: 3 )
    @persona.save
    if @persona.errors.empty?
      render :name
    else
      render :new
    end
  end

  def choix4
    @persona = Persona.new(name: Faker::JapaneseMedia::OnePiece.character, pv: 100, pa: 100, avatarnum: 4 )
    @persona.save
    if @persona.errors.empty?
      render :name
    else
      render :new
    end
  end

  def name
    Persona.update(Persona.last.id, pa: 0 )
  end

  # POST method for processing form data
  def create
    @persona = Persona.new(name: Faker::JapaneseMedia::OnePiece.character, pv: 100, pa: 100, avatarnum: @av )
    @persona.save
    if @persona.errors.empty?
      render :index
    else
      render :new
    end
  end

  # GET method for editing a persona based on id
  def edit
    @persona = Persona.find(params[:id])
  end

  # PUT method for updating in database a persona based on id
  def update
    Report.destroy_all
    Report.create(decription: "Fight!")
    @persona = Persona.find(params[:id])
    @persona.update(update_params)
    @persona.save
    if @persona.errors.empty?
      render :index
    else
      flash[:error] = 'Failed to edit persona!'
      render json: { errors: @persona.errors }, status: :forbiddden
      render :edit
    end
  end

  # DELETE method for deleting a persona from database based on id
  def destroy
    @persona = Persona.find(params[:id])
    if @persona.delete
      flash[:notice] = 'Persona deleted!'
      head :no_content
      render :index
    else
      flash[:error] = 'Failed to delete this persona!'
      render :destroy
    end
  end

  # we used strong parameters for the validation of params
  def create_params
    params.permit(:name, :pv, :pa)
  end

  def update_params
    params.require(:persona).permit(:name, :pv, :pa)
  end

  def attaque; end

  def you_attaque_cool
    unless Persona.last.pv.zero?
      pa = Persona.last.pa
      pv = Opponent.last.pv

      if Opponent.last.pv > 3
        Opponent.update(Opponent.last.id, pv: pv - Persona.last.pa / 30 )
        Report.create(decription: "You gave a Cool Attaque , IA looses #{Persona.last.pa / 30} points of PV.  You win 5 points points of PA . IA: PV=#{pv - Persona.last.pa / 30} / PA=#{Opponent.last.pa} . YOU: PV=#{Persona.last.pv} / PA=#{pa + 5}")
      else
        Opponent.update(Opponent.last.id, pv: 0 )
        Report.create(decription: "You gave a Cool Attaque , IA looses #{Persona.last.pa / 30} points of PV.  You win 5 points points of PA . IA: PV=ZERO / PA=#{Opponent.last.pa} . YOU: PV=#{Persona.last.pv} / PA=#{pa + 5}")
      end
      Persona.update(Persona.last.id, pa: pa + 5 )
    end
    if Persona.last.pv.zero?
      render :loose
    elsif Opponent.last.pv.zero?
      render :win
    else
      render :index2
    end
  end

  def you_attaque_medium
    unless Persona.last.pv.zero?
      pa = Persona.last.pa
      pv = Opponent.last.pv

      if Opponent.last.pv > 10
        Opponent.update(Opponent.last.id, pv: pv - Persona.last.pa / 10 )
        Report.create(decription: "You gave a Medium Attaque , IA looses #{Persona.last.pa / 10} points of PV.  You loose 5 points of PA . IA: PV=#{pv - Persona.last.pa / 10} / PA=#{Opponent.last.pa} . YOU: PV=#{Persona.last.pv} / PA=#{pa - 5}")
      else
        Opponent.update(Opponent.last.id, pv: 0 )
        Report.create(decription: "You gave a Medium Attaque , IA looses #{Persona.last.pa / 10} points of PV.  You loose 5 points of PA . IA: PV=ZERO / PA=#{Opponent.last.pa} . YOU: PV=#{Persona.last.pv} / PA=#{pa - 5}")
      end

      if Persona.last.pa > 5
        Persona.update(Persona.last.id, pa: pa - 5 )
      else
        Persona.update(Persona.last.id, pa: 0 )
      end
    end
    if Persona.last.pv.zero?
      render :loose
    elsif Opponent.last.pv.zero?
      render :win
    else
      render :index2
    end
  end

  def you_attaque_hard
    unless Persona.last.pv.zero?
      pa = Persona.last.pa
      pv = Opponent.last.pv

      if Opponent.last.pv > Persona.last.pa / 5
        Opponent.update(Opponent.last.id, pv: (pv - Persona.last.pa / 5) )
        Report.create(decription: "You gave a Hard Attaque , IA looses #{Persona.last.pa / 5} points of PV.  You loose 10 points of PA . IA: PV=#{pv - Persona.last.pa / 5} / PA=#{Opponent.last.pa} . YOU: PV=#{Persona.last.pv} / PA=#{pa - 10}")
      else
        Opponent.update(Opponent.last.id, pv: 0 )
        Report.create(decription: "You gave a Hard Attaque , IA looses #{Persona.last.pa / 5} points of PV.  You loose 10 points of PA . IA: PV=ZERO / PA=#{Opponent.last.pa} . YOU: PV=#{Persona.last.pv} / PA=#{pa - 10}")
      end

      if Persona.last.pa > 10
        Persona.update(Persona.last.id, pa: pa - 10 )
      else
        Persona.update(Persona.last.id, pa: 0 )
      end
    end
    if Persona.last.pv.zero?
      render :loose
    elsif Opponent.last.pv.zero?
      render :win
    else
      render :index2
    end
  end

  def win; end

  def loose; end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/choix.html.erb
<% content_for("page_header") do %>
 <%= stylesheet_link_tag 'application.css' %>
<% end %>


<div class="choix">

<div><%= render "layouts/persos/perso1d" %><%= button_to 'RYU', choix1_path, method: :get %></div>

<div><%= render "layouts/persos/perso2d" %><%= button_to 'KEN', choix2_path, method: :get %></div>

<div><%= render "layouts/persos/perso3d" %><%= button_to 'GOKU', choix3_path, method: :get %></div>

<div><%= render "layouts/persos/perso4d" %><%= button_to 'MONKEY D', choix4_path, method: :get %></div>

</div>

<div class="inst">CHOOSE YOUR CHARACTER</div>

app/views/personas/index.html.erb
<% content_for("page_header") do %>
 <%= stylesheet_link_tag 'application.css' %>
<% end %>


<div class="head">
  <%= render "layouts/topbanniere" %>
</div>

<div class="joystick">
  <form action="/you_attaque_cool" method="get">
    <input class="joy-btn" type="submit" value="SOFT" >  
  </form>
  <form action="/you_attaque_medium" method="get">
    <input class="joy-btn" type="submit" value="MEDIUM" >  
  </form>
  <form action="/you_attaque_hard" method="get">
    <input class="joy-btn" type="submit" value="HARD" >  
  </form>
</div>

<div class="arena">
	<%n=2%>
	<div>	
		<%= render "layouts/persos/perso#{Opponent.last.avatarnum}g" %>
		<% n-=1 %>
	</div>
	<% c = Persona.last.pv %>	
	<div class="separator"
		<% if c < 10 %>
			style="height: 10px ; width: 0px;" 
		<% elsif c >= 10 && c < 20 %>
			style="height: 10px ; width: 50px;"
		<% elsif c >= 20 && c < 30 %>
			style="height: 10px ; width: 100px;"
		<% elsif c >= 30 && c < 40 %>
			style="height: 10px ; width: 150px;"
		<% elsif c >= 40 && c < 50 %>
			style="height: 10px ; width: 200px;"
		<% elsif c >= 50 && c < 60 %>
			style="height: 10px ; width: 300px;"
		<% elsif c >= 60 && c < 70 %>
			style="height: 10px ; width: 400px;"
		<% elsif c >= 70 && c < 80 %>
			style="height: 10px ; width: 600px;"
		<% elsif c >= 80 && c < 100 %>
			style="height: 10px ; width: 800px;"
		<% else %>
			style="height: 10px ; width: 1200px;"
		<%end%> 
		></div>
	<div>	
		<%= render "layouts/persos/perso#{Persona.last.avatarnum}d" %>
	</div>
</div>

<div class="report">
  <%= render "layouts/report" %>
</div>

app/views/personas/index2.html.erb
<% content_for("page_header") do %>
 <%= stylesheet_link_tag 'application.css' %>
<% end %>


<div class="head">
  <%= render "layouts/topbanniere" %>
</div>

<div class="joystick">	  
  <%= button_to 'IA Turn', choose_action_path, method: :get %>
</div>



<div class="arena">
	<%n=2%>
	<div>	
		<%= render "layouts/persos/perso#{Opponent.last.avatarnum}g" %>
		<% n-=1 %>
	</div>
	<% c = Opponent.last.pv %>
		<div class="separator"
		<% if c < 10 %>
			style="height: 10px ; width: 0px;" 
		<% elsif c >= 10 && c < 20 %>
			style="height: 10px ; width: 50px;"
		<% elsif c >= 20 && c < 30 %>
			style="height: 10px ; width: 100px;"
		<% elsif c >= 30 && c < 40 %>
			style="height: 10px ; width: 150px;"
		<% elsif c >= 40 && c < 50 %>
			style="height: 10px ; width: 200px;"
		<% elsif c >= 50 && c < 60 %>
			style="height: 10px ; width: 300px;"
		<% elsif c >= 60 && c < 70 %>
			style="height: 10px ; width: 400px;"
		<% elsif c >= 70 && c < 80 %>
			style="height: 10px ; width: 600px;"
		<% elsif c >= 80 && c < 100 %>
			style="height: 10px ; width: 800px;"
		<% else %>
			style="height: 10px ; width: 1200px;"
		<%end%> 
		></div>
	<div>	
		<%= render "layouts/persos/perso#{Persona.last.avatarnum}d" %>
	</div>
</div>

<div class="report">
  <%= render "layouts/report" %>
</div>

app/views/personas/loose.html.erb
<div class="start">
  <form action="/personas/new" method="get">
    <input class="start-btn" type="submit" value="RESTART" >  
  </form>
</div>
<div id="result">YOU LOOSE</div>
<div class="reporting">
	<% Report.all.each do |r| %>
	<%= r.decription %>
	<br>
	<% end %>
</div>

app/views/personas/name.html.erb
<div class="start">
	<%= form_for @persona do |f| %>
	<div>YOUR NAME</div>

	<div>
		<%= f.text_field :name , :size => 30 %>
	</div>

	<div>
		<button type="submit">ok or change</button>
	</div>

	<% end %>
</div>

app/views/personas/new.html.erb
<div class="new">
<div class="start">
	<div>
	  <form action="/opponents" method="post">
	    <input class="start-btn" type="submit" value="START" >  
	  </form>
	</div>
</div>
</div>

app/views/personas/win.html.erb
<div class="start">
  <form action="/personas/new" method="get">
    <input class="start-btn" type="submit" value="RESTART" >  
  </form>
</div>
<div id="result"><p>YOU WIN</p></div>
<div class="reporting">
  	<% Report.all.each do |r| %>
  	<%= r.decription %>
  	<br>
  	<% end %>
</div>